name: Continuous Integration

on: [pull_request]

jobs:
  deploy:
    name: Build2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
